### ISSUE TITLE
ARS Align to new FrameworkAgreement Support

### ISSUE THREAD

**Issue by jjeroch** [eclipse-tractusx/ssi-authority-schema-registry#3]
## Summary
Adjust implementation/seeding of previous release 24.05. https://github.com/eclipse-tractusx/ssi-authority-schema-registry/issues/7 due to the new standard released in 24.08.

The seeding data need to get adjusted to only support the still available/supported credentials
(see "Task" column in the table below)

Credential Type | Credential | Authority | Task
-- | -- | -- | --
Business Partner Number | BusinessPartnerCredential | BPNL00000003CRHK | keep
Membership | MembershipCredential | BPNL00000003CRHK | keep
Framework | TraceabilityCredential | BPNL00000003CRHK | remove
Framework | QualityCredential | BPNL00000003CRHK | remove
Framework | CircularEconomyCredential | BPNL00000003CRHK | remove
Framework | PcfCredential | BPNL00000003CRHK | remove
Framework | DemandCapacityCredential | BPNL00000003CRHK | remove
Framework | PurisCredential | BPNL00000003CRHK | remove
Framework | BusinessPartnerCredential | BPNL00000003CRHK | remove
Framework | BehavioralTwinCredential | BPNL00000003CRHK | remove
CompanyRole | DismantlerCredential | BPNL00000003CRHK, BPNL00000003CRHL | keep
Framework | DataExchangeGovernanceCredential | BPNL00000003CRHK | add newly

----

Please use following test scenarios

### Test Case 1: Verify BusinessPartnerCredential is Kept
**Objective**: Ensure that the BusinessPartnerCredential is still present and linked to the correct authority.

**Steps to Execute**:
1. Query the seeding data for BusinessPartnerCredential.
2. Check that the credential exists.
3. Verify that the credential is linked to authority BPNL00000003CRHK.

**Expected Result**:
The BusinessPartnerCredential should be present and linked to the specified authority.

### Test Case 2: Verify MembershipCredential is Kept
**Objective**: Confirm that the MembershipCredential is preserved and associated with the correct authority.

**Steps to Execute**:
1. Query the seeding data for MembershipCredential.
2. Check that the credential exists.
3. Verify that the credential is linked to authority BPNL00000003CRHK.

**Expected Result**:
The MembershipCredential should be present and associated with the specified authority.

### Test Case 3: Verify Removal of TraceabilityCredential
**Objective**: Ensure that the TraceabilityCredential has been removed.

**Steps to Execute**:
1. Query the seeding data for TraceabilityCredential.
2. Check that the credential does not exist.

**Expected Result**:
The TraceabilityCredential should not be present in the seeding data.

### Test Case 4: Verify Removal of Remaining Framework Credentials
**Objective**: Confirm that all other Framework credentials are removed.

**Steps to Execute**:
1. Query the seeding data for each of the following credentials:
    - QualityCredential
    - CircularEconomyCredential
    - PcfCredential
    - DemandCapacityCredential
    - PurisCredential
    - BusinessPartnerCredential (under Framework)
    - BehavioralTwinCredential
2. Check that none of these credentials exist.

**Expected Result**:
None of the listed Framework credentials should be present in the seeding data.

### Test Case 5: Verify DismantlerCredential is Kept for Both Authorities
**Objective**: Ensure that the DismantlerCredential is kept and associated with both authorities.

**Steps to Execute**:
1. Query the seeding data for DismantlerCredential.
2. Check that the credential exists.
3. Verify that the credential is linked to both authorities BPNL00000003CRHK and BPNL00000003CRHL.

**Expected Result**:
The DismantlerCredential should be present and linked to both specified authorities.

### Test Case 6: Verify Addition of DataExchangeGovernanceCredential
**Objective**: Confirm that the DataExchangeGovernanceCredential is newly added and linked to the correct authority.

**Steps to Execute**:
1. Query the seeding data for DataExchangeGovernanceCredential.
2. Check that the credential exists.
3. Verify that the credential is linked to authority BPNL00000003CRHK.

**Expected Result**:
The DataExchangeGovernanceCredential should be present and linked to the specified authority.

### Test Reporting
The results of each test case should be documented, including any discrepancies between the expected and actual results. Any failures should trigger a defect report, and the development team should address the issues accordingly. Subsequent retesting should be performed to confirm that all issues have been resolved before the final sign-off.

**Comment by jjeroch** [comment]
Moved to 24.12.
Reason: limited capacity in 24.08.

**Comment by Sebastian-Wurm** [comment]
@jjeroch: is this already done?

**Comment by Phil91** [comment]
@Sebastian-Wurm not yet implemented, but will start working on it.
