### ISSUE TITLE
Authority & Schema Registry - DB Schema

### ISSUE THREAD

**Issue by jjeroch** [eclipse-tractusx/ssi-authority-schema-registry#7]
## Summary

Implement the "Authority & Schema Registry" db with the following schema

<img width="522" alt="image" src="https://github.com/eclipse-tractusx/portal-backend/assets/94133633/36993836-da15-4b50-a642-2ae3ea218a0c">

*please use "type" instead of "name"

#### Seeding example data (interim; will change till official release):

| Credential Type | Credential | Authority |
| ------------- | ------------- | ------------- |
| Business Partner Number  | BusinessPartnerCredential  | BPNL00000003CRHK  |
| Membership  | MembershipCredential  | BPNL00000003CRHK  |
| Framework  | TraceabilityCredential  | BPNL00000003CRHK  |
| Framework  | QualityCredential  | BPNL00000003CRHK  |
| Framework  | CircularEconomyCredential  | BPNL00000003CRHK  |
| Framework  | PcfCredential  | BPNL00000003CRHK  |
| Framework  | DemandCapacityCredential  | BPNL00000003CRHK  |
| Framework  | PurisCredential  | BPNL00000003CRHK  |
| Framework  | BusinessPartnerCredential  | BPNL00000003CRHK  |
| Framework  | BehavioralTwinCredential  | BPNL00000003CRHK  |
| CompanyRole  | DismantlerCredential  | BPNL00000003CRHK, BPNL00000003CRHL |

---

**Comment by Phil91** [comment]
@jjeroch could you please specify the Framework .... entry :)

**Comment by Phil91** [comment]
> @jjeroch could you please specify the Framework .... entry :)

clarified - framework ... is just a marker that there might be more framework credentials coming

**Comment by jjeroch** [comment]
@Phil91 
as we spoke; the seeding data table got updated/corrected.

**As-Is**

| Credential Type | Credential | Authority |
| ------------- | ------------- | ------------- |
| Business Partner Number  | BPNL  | BPNL00000003CRHK  |
| Membership  | CX Membership  | BPNL00000003CRHK  |
| Framework  | Framework Traceability  | BPNL00000003CRHK  |
| Framework  | Framework Sustainability  | BPNL00000003CRHK  |
| Framework  | Framework Quality  | BPNL00000003CRHK  |
| Framework  | Framework ....  | BPNL00000003CRHK  |
| CompanyRole  | Dismantler  | BPNL00000003CRHK, BPNL00000003CRHL |

**To-Be**

| Credential Type | Credential | Authority |
| ------------- | ------------- | ------------- |
| Business Partner Number  | BusinessPartnerCredential  | BPNL00000003CRHK  |
| Membership  | MembershipCredential  | BPNL00000003CRHK  |
| Framework  | TraceabilityCredential  | BPNL00000003CRHK  |
| Framework  | QualityCredential  | BPNL00000003CRHK  |
| Framework  | CircularEconomyCredential  | BPNL00000003CRHK  |
| Framework  | PcfCredential  | BPNL00000003CRHK  |
| Framework  | DemandCapacityCredential  | BPNL00000003CRHK  |
| Framework  | PurisCredential  | BPNL00000003CRHK  |
| Framework  | BusinessPartnerCredential  | BPNL00000003CRHK  |
| Framework  | BehavioralTwinCredential  | BPNL00000003CRHK  |
| CompanyRole  | DismantlerCredential  | BPNL00000003CRHK, BPNL00000003CRHL |

**Comment by Phil91** [comment]
implemented in #12
